### ISSUE TITLE
Is there documentation to know the shortcuts?

### ISSUE THREAD

**Issue by sirdavid32** [jiggymoon69/node_tabber#1]
Hi, this is a fantastic addon! A lifesaver. Is there a place to read all the possible commands to invoke after the tab press?
Thanks!

**Comment by jiggymoon69** [comment]
Not here at the moment. To be honest, probably easiest to use the standard default SHIFT-A blender method, where you will get a category ordered list of shaders/functions. Inherently the idea of the addon is to help you find what you know you are already searching for, so yes, unfortunately you are driving blind when you use it.
