### ISSUE TITLE
Can't install from repository zip

### ISSUE THREAD

**Issue by olimoth** [jiggymoon69/node_tabber#2]
Many blender add-ons can be installed by downloading the repository as a zip from github and then selecting that file from the "Install..." button in add-on preferences. That doesn't seem to work for this add-on, as the code is in a subdirectory.

Expected behaviour:
- Download zip from main repository page
- Install zip from add-ons preferences "Install..." button
- Add-on is now installed and available

Actual behaviour:
- Add on appears to install but is not available in add-ons list
- You must move the `node_tabber` subdirectory from `node_tabber-master` up one directory to make the add-on appear

edit: Apologies, I didn't notice the releases tab until just now. Maybe you could put a link there in the README for people like me who miss it 😉

**Comment by jiggymoon69** [comment]
Hi Olimoth, easy mistake, Ill fix right away.

Enjoy NT!

**Comment by crossm0d** [comment]
Thanks, and I'm enjoying it very much. I was already hitting search and typing things like "ping pong". Now that actually does what I want!
